#!/usr/bin/env bash

# Update package index and install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Create a custom 404 page
echo '<!DOCTYPE html>
<html>
<head>
<title>404 Not Found</title>
</head>
<body>
<h1>404 Not Found</h1>
<p>Ceci n'\''est pas une page</p>
</body>
</html>' | sudo tee /var/www/html/404.html >/dev/null

# Configure nginx to use the custom 404 page
sudo sed -i '/^.*server_name.*;/a \\n\terror_page 404 /404.html;\n' /etc/nginx/sites-available/default

# Restart nginx to apply changes
sudo service nginx restart
