#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
sudo apt-get update
sudo apt install -y haproxy

# Configure Haproxy to send traffic to web-01 and web-02
echo '
frontend nenenj_frontend
	mode http
        bind *:80
	default_backend nenenj_backend

backend nenenj_backend
	mode http
	balance roundrobin
	server 158410-web-01 52.3.251.115:80
	server 158410-web-02 54.208.17.71:80
	timeout connect 30s
	timeout server 30s
' | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Enable HAproxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

#Restart Haproxy
sudo service haproxy restart
