#!/usr/bin/env bash

# Check if the username argument is provided
if [ $# -ne 1 ]; then
	echo "Usage: $0 <username>"
	exit 1
fi
# Runs whoami command as the user provided in argument
sudo -u "$1" whoami
