#!/usr/bin/env bash
# Fixes server bug
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default

# Stop Apache2 if running
if pgrep apache2 >/dev/null; then
	pkill apache2
fi

# restart
su nginx -s /bin/bash -c 'service nginx restart'
